### ISSUE TITLE
Rails 4 + Mongoid + Tire - Document(s) not found for class

### ISSUE THREAD

**Issue by jonarrien** [karmi/retire#775]
When using tire.search method inside a Mongoid::Document with **load: true** param, doesn't retrieve documents from Mongo. 

```
Problem:
  Document(s) not found for class Customer with id(s) {"$oid"=>"51cea19ca8bab75de2000001"}.
Summary:
  When calling Customer.find with an id or array of ids, each parameter must match a document in the database or this error will be raised. The search was for the id(s): {"$oid"=>"51cea19ca8bab75de2000001"} ... (1 total) and the following ids were not found: {"$oid"=>"51cea19ca8bab75de2000001"}.
```

The document in database that can't find:

```
{ "_id" : ObjectId( "51cea19ca8bab75de2000001" ),
  "customer_type"....
```

**Comment by jonarrien** [comment]
I forgot to include the trace:

```
   () Users/jon/.rvm/gems/ruby-2.0.0-p195/bundler/gems/mongoid-e1b32e598ec2/lib/mongoid/criteria.rb:470:in `check_for_missing_documents!'
   () Users/jon/.rvm/gems/ruby-2.0.0-p195/bundler/gems/mongoid-e1b32e598ec2/lib/mongoid/criteria/findable.rb:20:in `execute_or_raise'
   () Users/jon/.rvm/gems/ruby-2.0.0-p195/bundler/gems/mongoid-e1b32e598ec2/lib/mongoid/criteria/findable.rb:40:in `find'
   () Users/jon/.rvm/gems/ruby-2.0.0-p195/bundler/gems/mongoid-e1b32e598ec2/lib/mongoid/findable.rb:88:in `find'
   () Users/jon/.rvm/gems/ruby-2.0.0-p195/bundler/gems/tire-07e69c810cb4/lib/tire/results/collection.rb:156:in `__find_records_by_ids'
   () Users/jon/.rvm/gems/ruby-2.0.0-p195/bundler/gems/tire-07e69c810cb4/lib/tire/results/collection.rb:144:in `block in __get_results_with_load'
   () Users/jon/.rvm/gems/ruby-2.0.0-p195/bundler/gems/tire-07e69c810cb4/lib/tire/results/collection.rb:131:in `__get_results_with_load'
   () Users/jon/.rvm/gems/ruby-2.0.0-p195/bundler/gems/tire-07e69c810cb4/lib/tire/results/collection.rb:27:in `results'
   () Users/jon/.rvm/gems/ruby-2.0.0-p195/bundler/gems/tire-07e69c810cb4/lib/tire/results/collection.rb:35:in `each'
  app/views/customers/index.html.haml:106:in `_app_views_customers_index_html_haml___1406913769269704192_70321301039100'
  actionpack (4.0.0) lib/action_view/template.rb:143:in `block in render'
  activesupport (4.0.0) lib/active_support/notifications.rb:161:in `instrument'
  actionpack (4.0.0) lib/action_view/template.rb:141:in `render'
  actionpack (4.0.0) lib/action_view/renderer/template_renderer.rb:49:in `block (2 levels) in render_template'
  actionpack (4.0.0) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
  activesupport (4.0.0) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.0.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
```

**Comment by phoet** [comment]
@jonarrien is `{"$oid"=>"51cea19ca8bab75de2000001"}` the id of the document in elasticsearch? is that a nested document? i saw an incompatibility note in mongoid about the `"$oid"` part: https://github.com/mongoid/mongoid/blob/master/CHANGELOG.md

**Comment by paulgoetze** [comment]
For me it is the same as for @jonarrien  - for a non nested document. I'm running Rails 4.0.0, Mongoid 4.0 and Tire 0.6.0. 

Additionally there is a strange switch of the ealsticsearch index entry ids:
For automatic generation while creating a document from the app an index entry looks like this with a document id as above: 

```
         {
            "_index": "products",
            "_type": "product",
            "_id": "{\"$oid\"=>\"51d6e9a993b6a2a751000005\"}",
            "_score": 14.054651,
            "_source": {
               "id": {
                  "$oid": "51d6e9a993b6a2a751000005"
               },
               "name": "Product",
               "price": "10.0",
               "published_at": "2013-07-04T12:00:00.000Z"
            }
         }
```

and if I import the models to the index by

`rake environment tire:import CLASS=Product FORCE=true`

then I got something like: `9M-8v3lqT_q7k4F4XdzfgA` as the entry's _id

What could be the matter with this?

**Comment by karmi** [comment]
Found the culprit, ironically enough, it's a specific fix for Mongoid .) -- karmi/tire@98e6dc7 changed `Tire::Index#get_id_from_document` to use `document.id.as_json` instead of `document.id`.

Now, let's observe:

``` ruby
Mongoid::VERSION
# => "3.1.4"
a = Article.first
# => #<Article _id: 51af2247410b5ac9ae000001, title: "Mongoid Title 1", content: "Lorem", published_on: 2013-06-05 11:34:31 UTC>
a.id
# => "51af2247410b5ac9ae000001"
a.id.as_json
# => "51af2247410b5ac9ae000001"
a.id.class
# => Moped::BSON::ObjectId

Mongoid::VERSION
# => "4.0.0"
a = Article.first
# => #<Article _id: 51af2247410b5ac9ae000001, title: "Mongoid Title 1", content: "Lorem">
a.id.class
# => Moped::BSON::ObjectId
a.id
# => "51af2247410b5ac9ae000001"
a.id.as_json
# => {"$oid"=>"51af2247410b5ac9
```

The linked commit contains links to relevant issues. Seems to me like simply reverting the commit should work, but I'd prefer to understand how Mongoid understands JSON serialization of models in general, and unless really neccessary, keep compatibility with Mongoid 3.x and 4.x.

Also, seems like the 4.0 version of Mongoid has not been yet released to Rubygems: https://rubygems.org/gems/mongoid/versions

**Comment by phoet** [comment]
would it make sense to create a cross-reference-issue in mongoid to let them know about such things breaking tire and possible other libraries?

**Comment by bhbryant** [comment]
Reverting karmi/tire@98e6dc7 will not fix the problem with Mongoid 4, you must explicitly cast the id to a string.

For those looking for a temporary fix, add the following to an initializer:

``` ruby
require "tire"
module Tire
  class Index
    def get_id_from_document(document)
     case
        when document.is_a?(Hash)
          document[:_id] || document['_id'] || document[:id] || document['id']
        when document.respond_to?(:id) && document.id != document.object_id
          document.id.to_s   # was document.id.as_json
      end
    end
  end
end
```

**Comment by karmi** [comment]
@jonarrien Should be solved by the closing commit, can you validate?

**Comment by jonarrien** [comment]
Sorry @karmi , I have been a bit a busy. I will test it on my rails4 branch as soon as I can, but looks my suspicions about the oid have been confirmed. Thanks

**Comment by ghost** [comment]
I'm using searckick(based on tire) with mongoid. For the time being this worked for me: 
I created mongoid.rb in config/initialisers and placed this code

module BSON
  class ObjectId
    def to_json(*args)
      to_s.to_json
    end

```
def as_json(*args)
  to_s.as_json
end
```

  end
end

**Comment by jeremylynch** [comment]
Is there any update on this issue? It is still occurring for me with tire 0.6.2 and Mongoid 4.0.0

@canercak's solution provides a temporary fix

**Comment by jonarrien** [comment]
@karmi yes, I got it working. Thanks and sorry for not answering sooner.  
@mrjlynch Maybe you can try using _id.to_s in the "to_indexed_json" method to ensure.
